package com.alejandromejia.marvelapp.utils


const val GET_ALL_CHARACTERS = "/v1/public/characters"
const val GET_CHARACTER_BY_NAME = "/v1/public/characters"
const val GET_CHARACTER_BY_ID = "/v1/public/characters/{characterId}"
const val GET_COMICS_BY_CHARACTER_ID = "/v1/public/characters/{characterId}/comics"
const val GET_COMICS_BY_ID = "/v1/public/comics/{comicId}"

const val DB_NAME = "MarvelDb"
const val HTTP = "http"
const val HTTPS = "https"
const val STATUS_MESSAGE = "status_message"
const val SCAFFOLD_MAIN_VIEW = "scaffoldMainView"
const val SCAFFOLD_DETAIL_VIEW = "scaffoldDetailView"
const val NO_DATA_FOUND = " No Data Found "
const val NO_CONTENT_DESCRIPTION = "No Content Description"
const val DESCRIPTION = "DESCRIPTION"
const val MODIFIED_DATE = "Modified Date"
const val PAGES = "Pages"
const val FORMAT = "Format"
const val EMPTY_STRING = ""
const val DETAIL_SCREEN = "detailScreen"
const val COMIC_SCREEN = "comicScreen"
const val FAVORITE_SCREEN = "favoriteScreen"
const val SEARCH_SCREEN = "searchScreen"
const val HOME_SCREEN = "homeScreen"
const val CANCEL = "Cancel"
const val SEARCH = "Search"
const val HOME = "Home"
const val FAVORITE = "favorite"
const val FAVORITES = "favorites"
const val RECENT_SEARCH = "Recent Search"
const val POPULAR_CHARACTERS = "Popular Characters"
const val CHARACTERS = "Characters"
const val COMICS = "Comics"
const val ONE_STR = "1"
const val ZERO = 0
const val ZERO_LONG = 0L